language: python
matrix:
  include:
  - python: 3.5
    dist: xenial
    env: TOXENV=django2.2
  - python: 3.6
    dist: xenial
    env: TOXENV=django2.2
  - python: 3.7
    dist: xenial
    env: TOXENV=django2.2
  - python: 3.5
    env: TOXENV=django2.1
  - python: 3.6
    env: TOXENV=django2.1
  - python: 3.7
    dist: xenial
    env: TOXENV=django2.1
install:
  - pip install tox
script:
  - tox
